name: My First Workflow

on: push 

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: welcome message
      run: | 
        echo "This is my first job"
        ls -la
        cat README.md
      
    - name: generate ASCII artwork
      run: cowsay -f dragon "Run for cover ... I am Dragon ... RAWR" >> dragon.txt
      
    
    # - name: list files
    #   run: ls

    # - name: read readme file
    #   run: cat README.md
      