name: Generating ASCII Artwork

on: push 

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout action
      uses: actions/checkout@v4
    
    - name: running shell script
      run: |
        chmod +x script.sh
        ./script.sh
    
    - name: list repo files
      run: ls
    
  
      