name: Generating ASCII Artwork

on: 
  # push
  workflow_dispatch 

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay 
      run: sudo apt-get install cowsay -y
    
    - name: generate ASCII artwork
      run: cowsay -f dragon "Run for cover ... I am Dragon ... RAWR" >> dragon.txt

    - name: Run artwork
      run: cat dragon.txt

    - name: Test file exist
      run: grep -i "dragon" dragon.txt

    - name: adding action upload artifact
      uses: actions/upload-artifact@v4
      with: 
        name: my-dragon-artifact
        path: dragon.txt 

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps: 
    - name: downloading artifact
      uses: actions/download-artifact@v4
      with: 
        name: my-dragon-artifact

    - name: sleep in 300 seconds
      run: sleep 300
    
    - name: test file exists
      run: grep -i "dragon" dragon.txt
    
  third-job: 
    needs: [first-job,second-job]
    runs-on: ubuntu-latest
    steps:
    - name: downloading artifact
      uses: actions/download-artifact@v4
      with: 
        name: my-dragon-artifact

    - name: read the file
      run: cat dragon.txt
    
    - name: display random 
      run: echo Displays .... ....
      