name: Generating ASCII Artwork

on: push 

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Install cowsay 
      run: sudo apt-get install cowsay -y
    
    - name: generate ASCII artwork
      run: cowsay -f dragon "Run for cover ... I am Dragon ... RAWR" >> dragon.txt

    - name: Run artwork
      run: cat dragon.txt

    - name: Test file exist
      run: grep -i "dragon" dragon.txt

    - name: welcome message
      run: | 
        echo "This is my first job"
        ls -la
        cat README.md
  
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps: 
    - name: sleep in 10 seconds
      run: sleep 10
    
    - name: test file exists
      run: grep -i "dragon" dragon.txt
    
  third-job: 
    needs: [first-job,second-job]
    runs-on: ubuntu-latest
    steps:
    - name: read the file
      run: cat dragon.txt
    
    - name: display random 
      run: echo Displays .... ....
      